#!/usr/bin/env node
// Builds the single file people paste into Google Apps Script.
//   node tools/build.js          → dist/Code.gs (the public, empty template)
//   node tools/build.js --org    → org/build/Code.gs + appsscript.json: the same, with your organisation's settings,
//                                  team, links and questions baked in, so the setup wizard fills every tab for you.
'use strict';
const fs = require('fs'), path = require('path');
const { ROOT, ORDER, read, readOrg } = require('./lib');

const withOrg = process.argv.includes('--org');
const header = '// nonprofit-360 — a free, open-source 360-degree evaluation for nonprofits (MIT license).\n' +
  '// Paste this whole file into Extensions → Apps Script → Code.gs, save, reload the sheet, then use the «360» menu.\n' +
  '// Generated by tools/build.js from src/ — edit the files in src/, not this one.\n\n';
let code = header + ORDER.map(f => '// ===== ' + f + ' =====\n' + read(f).trim() + '\n').join('\n');

let outDir = path.join(ROOT, 'dist');
if (withOrg) {
  const org = readOrg();
  const seed = { settings: org.settings, team: org.team, links: org.links, never: org.never, deptLinks: org.deptLinks, questions: org.questions };
  code += '\n// ===== your organisation (from the private org/ folder — never commit this file) =====\nORG_SEED = ' + JSON.stringify(seed, null, 1) + ';\n';
  outDir = path.join(org.dir, 'build');
}
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'Code.gs'), code);
fs.copyFileSync(path.join(ROOT, 'appsscript.json'), path.join(outDir, 'appsscript.json'));
console.log('Built ' + path.relative(ROOT, path.join(outDir, 'Code.gs')) + ' (' + Math.round(code.length / 1024) + ' KB)' + (withOrg ? ' with your organisation\'s data' : ''));
