/**
 * nonprofit-360 — every English word the tool shows. Arabic is in Strings.ar.gs with the same keys.
 * {name}-style placeholders are filled in at run time. AI-drafted: have a native speaker review before a real cycle.
 */
var STR_EN = {
  // ——— defaults the organisation can change in Settings ———
  'default.orgName': 'Our organisation',
  'default.cycle': String(new Date().getFullYear()),
  'default.period': 'since the start of the year',
  'default.tagline': 'Growing together',
  'default.signature': 'The leadership team',
  'default.value1.name': 'Excellence', 'default.value1.text': 'Do this evaluation as carefully as your work: if you choose 1, 2 or 5, write a real example that explains why.',
  'default.value2.name': 'Sincerity', 'default.value2.text': 'Our intention is to help each other grow — no flattery and no blame.',
  'default.value3.name': 'Trust', 'default.value3.text': 'Rate only what you have seen yourself. What you write is held in trust: the person you rate will not know it was you, only the evaluation admin sees individual answers, and your written notes may reach the person without your name — so write kindly, without details that reveal who you are.',
  'default.value4.name': 'Transparency', 'default.value4.text': 'Say what is true, clearly and kindly, the way you would like it said to you.',

  // ——— tab names ———
  'tab.GUIDE': 'Start here', 'tab.SETTINGS': 'Settings', 'tab.TEAM': 'Team', 'tab.LINKS': 'Work links', 'tab.NEVER': 'Never pair',
  'tab.DEPTLINKS': 'Department links', 'tab.QUESTIONS': 'Questions', 'tab.ASSIGN': 'Who rates whom', 'tab.DECISIONS': 'Review decisions',
  'tab.RESPONSES': 'Answers (do not edit)', 'tab.DRAFTS': 'Unsent drafts', 'tab.COMPLETION': 'Progress', 'tab.FLAGS': 'Flags',
  'tab.PEOPLE': 'Results by person', 'tab.HEAT': 'Heat map', 'tab.DEPTS': 'Departments', 'tab.STARS': 'Recognition',
  'tab.BLAME': 'Managers and teams', 'tab.ACCOUNT': 'Manager accountability', 'tab.SUMMARY': 'Summary', 'tab.DASH': 'Dashboard',

  // ——— menu ———
  'menu.start': 'Start setup', 'menu.title': '360 evaluation', 'menu.setup': '1) Setup and settings', 'menu.check': '2) Check my team and links',
  'menu.pairs': '3) Make the pairings (who rates whom)', 'menu.publish': '4) Publish the personal page', 'menu.preview': '5) Send me a preview',
  'menu.invite': '6) Send the invitations to the team', 'menu.update': 'Update results', 'menu.remind': 'Send reminders to people who have not finished',
  'menu.reports': 'Make the reports (admin only)', 'menu.paper': 'Make paper forms for people without email', 'menu.paperEntry': 'Enter answers from paper forms',
  'menu.testRun': 'Try it: run a test with made-up people', 'menu.testClear': 'Try it: clear the test', 'menu.newRound': 'Start a new round (clears answers, keeps team and settings)',

  // ——— setup wizard ———
  'wiz.title': 'Set up your 360 evaluation',
  'wiz.intro': 'Fill in what you know; you can change everything later in the Settings tab. Nothing is sent to anyone.',
  'wiz.values': 'Your values', 'wiz.valuesHelp': 'Up to four values shown to everyone before they start, each with one line on what it means in this evaluation. Leave a name empty to skip it.',
  'wiz.example': 'Fill the Team tab with a made-up example team, so I can try it first',
  'wiz.seed': 'Your team, work links and questions prepared with Claude Code will be written into the tabs.',
  'wiz.save': 'Save and build my tabs', 'wiz.saving': 'Building…',
  'wiz.saved': 'Done. Your tabs are ready. Next: fill or check the Team and Work links tabs, then choose «2) Check my team and links» from the menu.',
  'wiz.renamed': 'Tab names now follow the new language.',

  // ——— settings (name and meaning) ———
  'col.settings.id': 'Id (do not edit)', 'col.settings.name': 'Setting', 'col.settings.value': 'Your value', 'col.settings.help': 'What it means',
  'set.LANGUAGE': 'Language', 'set.LANGUAGE.help': 'en = English, ar = Arabic (right-to-left). Everything people see follows this.',
  'set.ORG_NAME': 'Organisation name', 'set.ORG_NAME.help': 'Shown on the page, emails and reports.',
  'set.CYCLE_NAME': 'Name of this evaluation round', 'set.CYCLE_NAME.help': 'For example 2026, or "Mid-year 2026".',
  'set.DEADLINE': 'Deadline', 'set.DEADLINE.help': 'The last day to fill in the evaluation. Shown to everyone.',
  'set.ADMIN_EMAIL': 'Admin email', 'set.ADMIN_EMAIL.help': 'The only person who can run the menu, see results, and enter paper forms. Usually the executive director or HR lead.',
  'set.SIGNATURE': 'Signature', 'set.SIGNATURE.help': 'Who the messages come from, for example "Dina Ali — Executive Director".',
  'set.TIME_ZONE': 'Time zone', 'set.TIME_ZONE.help': 'For example Europe/London or Asia/Dubai. Empty = the sheet\'s time zone.',
  'set.LOGO': 'Logo', 'set.LOGO.help': 'A link to your logo: a Google Drive file link or an image web address. Empty = your name in text.',
  'set.COLOR_PRIMARY': 'Main colour', 'set.COLOR_PRIMARY.help': 'A colour code like #1f5f8b.',
  'set.COLOR_ACCENT': 'Second colour', 'set.COLOR_ACCENT.help': 'A lighter colour code for charts, like #35b0d8.',
  'set.TAGLINE': 'Tagline', 'set.TAGLINE.help': 'A short line under your logo.',
  'set.VALUE_1_NAME': 'Value 1', 'set.VALUE_1_NAME.help': '', 'set.VALUE_1_TEXT': 'What value 1 means here', 'set.VALUE_1_TEXT.help': '',
  'set.VALUE_2_NAME': 'Value 2', 'set.VALUE_2_NAME.help': '', 'set.VALUE_2_TEXT': 'What value 2 means here', 'set.VALUE_2_TEXT.help': '',
  'set.VALUE_3_NAME': 'Value 3', 'set.VALUE_3_NAME.help': '', 'set.VALUE_3_TEXT': 'What value 3 means here', 'set.VALUE_3_TEXT.help': '',
  'set.VALUE_4_NAME': 'Value 4', 'set.VALUE_4_NAME.help': '', 'set.VALUE_4_TEXT': 'What value 4 means here', 'set.VALUE_4_TEXT.help': '',
  'set.ORG_TARGETS': 'Organisation targets (optional)', 'set.ORG_TARGETS.help': 'One or two lines on this year\'s targets, shown in the self-evaluation question about each person\'s share of the team\'s numbers.',
  'set.PAGE_URL': 'Personal page address', 'set.PAGE_URL.help': 'Filled in when you publish the page (menu 4). It ends with /exec.',
  'set.MIN_GROUP': 'Minimum group size', 'set.MIN_GROUP.help': 'Results of a group are shown only when at least this many people rated. Protects who said what. Default 3.',
  'set.EVIDENCE_MIN_CHARS': 'Shortest example allowed', 'set.EVIDENCE_MIN_CHARS.help': 'Number of characters an example needs after a 1, 2 or 5. Default 30.',
  'set.MANAGERS_RATE_EACH_OTHER': 'Managers rate each other', 'set.MANAGERS_RATE_EACH_OTHER.help': 'yes = the managers who report to the head of the organisation all rate each other.',
  'set.TOP_RATED_BY_DIRECTS_ONLY': 'Head rated by direct reports only', 'set.TOP_RATED_BY_DIRECTS_ONLY.help': 'yes = the head of the organisation is rated only by the people who report to them.',
  'set.DEPT_RATINGS': 'Departments rate each other', 'set.DEPT_RATINGS.help': 'yes = each person also rates the departments their team works with.',
  'set.BLIND_SPOT': 'Blind-spot gap (advanced)', 'set.BLIND_SPOT.help': 'Self-rating this much above others is flagged.',
  'set.OUTLIER': 'Outlier gap (advanced)', 'set.OUTLIER.help': 'One rater this far from the others is flagged.',
  'set.MUTUAL_HIGH': 'Mutual high rating (advanced)', 'set.MUTUAL_HIGH.help': 'Two colleagues rating each other at or above this are flagged.',
  'set.BLAME_GAP': 'Manager harshness gap (advanced)', 'set.BLAME_GAP.help': 'A manager rating the team this much below others do (negative number).',
  'set.BLAME_UPWARD_MAX': 'Team view of leadership (advanced)', 'set.BLAME_UPWARD_MAX.help': '…while the team rates the leadership at or below this.',
  'set.WEAK_EVIDENCE_CHARS': 'Weak example length (advanced)', 'set.WEAK_EVIDENCE_CHARS.help': 'Examples shorter than this are flagged as weak.',

  // ——— columns and notes of the tabs the admin fills ———
  'col.team.name': 'Name', 'col.team.email': 'Work email (empty = paper)', 'col.team.dept': 'Department', 'col.team.title': 'Job title',
  'col.team.manager': 'Manager (email or name)', 'col.team.active': 'Included (yes/no)', 'col.team.note': 'Note',
  'note.team': 'One row per person. Manager = the email or the exact name of their direct manager; leave it empty only for the head of the organisation. A person with no work email is rated online and rates others on a paper form.',
  'note.paperPerson': 'No work email: rated online, rates others on paper',
  'col.links.rater': 'Person who rates (email or name)', 'col.links.ratee': 'Person rated (email or name)', 'col.links.reason': 'Why (shown to the rater)',
  'col.links.both': 'Both directions (yes/no)', 'col.links.note': 'Note',
  'note.links': 'Add the people who really work together outside their own team, with the reason. Managers and their teams are added automatically, so do not list them here. Nobody is paired at random.',
  'col.never.a': 'Person A', 'col.never.b': 'Person B', 'col.never.note': 'Note',
  'note.never': 'These two never rate each other, in either direction, whatever rule would pair them.',
  'col.deptlinks.dept': 'Department', 'col.deptlinks.rates': 'Rates these departments (separated by commas)',
  'note.deptlinks': 'Which departments each department rates. A department with no row rates every other department. Turn department ratings off in Settings if you do not want them.',
  'col.questions.code': 'Code (do not change)', 'col.questions.section': 'Section', 'col.questions.question': 'Question', 'col.questions.help': 'Explanation (one line per point)',
  'col.questions.required': 'Required', 'col.questions.depts': 'Only for departments (optional)', 'col.questions.active': 'In use (yes/no)',
  'note.questions': 'Reword any question freely. Keep the codes: the analysis uses them. To add a question, add a row with a new code (for example C9 in the core section). To switch one off, write "no" under In use.',
  'col.assign.raterEmail': 'Rater email', 'col.assign.rater': 'Rater', 'col.assign.rateeEmail': 'Rated email', 'col.assign.ratee': 'Rated',
  'col.assign.rel': 'Relationship', 'col.assign.reason': 'Reason', 'col.assign.done': 'Done?',
  'note.assign': 'Made by menu 3. You may delete a row or add one by hand before inviting the team. Every row needs a reason.',
  'col.decisions.rater': 'Rater email', 'col.decisions.ratee': 'Rated email', 'col.decisions.decision': 'Decision (keep / exclude)', 'col.decisions.reason': 'Why', 'col.decisions.date': 'Date',
  'col.responses.date': 'Date', 'col.responses.kind': 'Kind', 'col.responses.rater': 'Rater', 'col.responses.ratee': 'Rated', 'col.responses.freq': 'How often', 'col.responses.data': 'Answers',
  'col.drafts.saved': 'Last saved', 'col.drafts.rater': 'Rater', 'col.drafts.key': 'Task', 'col.drafts.data': 'Draft',
  'word.yes': 'yes', 'word.no': 'no', 'word.ifLow': 'if low', 'word.keep': 'keep', 'word.exclude': 'exclude',
  'section.CORE': 'Core — everyone', 'section.LEAD': 'Leadership — managers', 'section.DEPT': 'Department → department', 'section.HEAD_ITEMS': 'Rated by the manager only', 'section.ROLE': 'Role — only for the departments listed',
  'section.SELF_OPEN': 'Self-evaluation — open', 'section.SELF_HEAD': 'Self-evaluation — managers', 'section.HEAD_OPEN': 'Manager\'s own part', 'section.MEMBER_OPEN': 'Member about their manager',
  'section.PERSON_OPEN': 'Notes when rating anyone',

  // ——— "Start here" tab ———
  'guide.title': '360 evaluation — {org}',
  'guide.private': 'Private: this file and every result in it are for the admin only. Do not share it.',
  'guide.step1': '1) Menu «360 evaluation» → «1) Setup and settings»: your name, language, values, deadline. You can change them any time.',
  'guide.step2': '2) Tab «Team»: one row per person with their department and manager. Write "no" under Included for anyone who should not take part.',
  'guide.step3': '3) Tab «Work links»: who else works closely with whom, and why. Managers and teams are added automatically. Or let managers fill it in: menu «Ask managers who works with whom».',
  'guide.step4': '4) Menu «2) Check my team and links»: fixes are explained in plain words.',
  'guide.step5': '5) Menu «3) Make the pairings»: then read the «Who rates whom» tab; every pair has its reason.',
  'guide.step6': '6) Menu «4) Publish the personal page»: follow the steps once. Then menu «5) Send me a preview» to see the email.',
  'guide.step7': '7) Menu «6) Send the invitations»: everyone gets one email with one button to their personal page.',
  'guide.step8': '8) While people answer: «Update results» → tab «Progress». «Send reminders» for people who have not finished.',
  'guide.step9': '9) Tab «Flags»: doubtful ratings, with names, for you only. In «Review decisions» write keep or exclude; your word beats the automatic rules.',
  'guide.step10': '10) «Make the reports»: for each person, your full copy and an employee copy with no names, plus an organisation report, in a private folder.',
  'guide.step11': '11) Nobody sees any result until you decide to share it. Share each employee copy yourself, in a conversation.',
  'guide.step12': '12) People without a work email: «Make paper forms» and print them. When they come back: «Enter answers from paper forms», click the name, and type the answers.',
  'guide.help': 'Stuck? Open the project in Claude Code and type /fix-360, or read docs/troubleshooting in the project.',

  // ——— checks ———
  'check.noTeam': 'The Team tab is empty. Add one row per person.',
  'check.duplicate': 'The email {who} appears twice in the Team tab.',
  'check.noTop': 'Nobody is at the top: exactly one person (the head of the organisation) should have an empty Manager cell.',
  'check.manyTops': 'Several people have no manager: {names}. Usually only the head of the organisation has none.',
  'check.badEmail': '{name}: "{email}" does not look like an email address.',
  'check.selfManager': '{name} is written as their own manager.',
  'check.managerMissing': '{name}: the manager "{manager}" is not in the Team tab (use their email or their name exactly as written).',
  'check.managerInactive': '{name}: their manager is marked "not included".',
  'check.managerNoEmail': '{name}: their manager has no work email, so the manager will rate them on paper.',
  'check.noDept': '{name} has no department.',
  'check.loop': '{name}: the manager chain goes round in a circle.',
  'check.linkUnknown': 'Work links row {row}: "{who}" is not in the Team tab.',
  'check.linkSelf': 'Work links row {row}: a person cannot rate themselves.',
  'check.linkNoReason': 'Work links row {row}: add a reason; the rater sees it.',
  'check.neverUnknown': 'Never pair row {row}: someone is not in the Team tab.',
  'col.actions.round': 'Round',
  'check.roleNoDept': 'Questions tab: the role question «{q}» is in use but lists no department, so nobody gets it. Write the departments it is for.',
  'check.roleDeptUnknown': 'Questions tab: «{q}» is for the department «{dept}», but nobody in the Team tab is in it. Write the department name exactly as in the Team tab.',
  'check.deptUnknown': 'Department links: "{dept}" is not a department in the Team tab.',
  'check.adminNotInTeam': 'The admin ({email}) is not in the Team tab. That is fine if the admin is not being evaluated.',
  'check.noDeadline': 'No deadline yet (Settings → Deadline).',
  'check.fewRaters': '{name} would be rated by only {n}; results are shown only with {min} or more. Consider adding a work link.',
  'check.heavy': '{name} would rate {n} people. That is a lot; consider fewer work links.',
  'check.allGood': 'Everything looks right. {n} pairings are ready: choose «3) Make the pairings».',
  'check.errorsTitle': 'Please fix {n} thing(s) first:',
  'check.warnsTitle': '{n} note(s) to consider:',
  'check.canPair': 'You can make the pairings now: {n} would be created.',
  'check.sameName': 'Two people are called «{name}». Managers and links written by name will match the first one; use emails for them.',
  'round.confirm': 'Start a new round? This clears every answer, unsent draft, review decision, pairing and result in this sheet. The team, work links, questions and settings stay. This cannot be undone.',
  'round.done': 'New round ready. Next: update the round name and deadline in Settings, check the Team tab, make the pairings, publish the personal page (in a copy of the sheet this is a new address), send yourself a preview, then invite the team.',
  'pairs.replace': 'There is already a list of who rates whom. Replacing it removes any row you added or deleted by hand. Continue?',
  'pairs.done': '{n} pairings made, each with its reason. Read the «Who rates whom» tab before inviting anyone.',

  // ——— publishing the page ———
  'publish.step1': 'At the top of this sheet: Extensions → Apps Script. Then, top right: Deploy → New deployment.',
  'publish.step2': 'Click the gear next to "Select type" and choose "Web app".',
  'publish.step3': 'Execute as: "Me". Who has access: "Anyone within <your organisation>". Then Deploy.',
  'publish.step4': 'Google asks for permission the first time: choose your account and allow. This lets the page save answers into this sheet.',
  'publish.step5': 'Copy the "Web app" address (it ends with /exec) and paste it below.',
  'publish.step6': 'After any change to the code later: Deploy → Manage deployments → pencil → Version: "New version" → Deploy. Check it says a new version number; the address stays the same.',
  'publish.current': 'Current page address:', 'publish.none': 'not published yet.',
  'publish.paste': 'Paste the Web app address:', 'publish.save': 'Save the address',
  'publish.bad': 'That does not look like a Web app address. It starts with https://script.google.com/ and ends with /exec.',
  'publish.saved': 'Saved. Next: «5) Send me a preview».',

  // ——— relationships ———
  'rel.SELF': 'Self', 'rel.HEAD_TO_MEMBER': 'Manager', 'rel.MEMBER_TO_HEAD': 'Their team', 'rel.PEER_SAME': 'Colleague — same department', 'rel.PEER_OTHER': 'Colleague — other department', 'rel.null': '—',
  'relFor.HEAD_TO_MEMBER': 'In your team', 'relFor.MEMBER_TO_HEAD': 'Your manager', 'relFor.PEER_SAME': 'Colleague in your department', 'relFor.PEER_OTHER': 'Colleague from another department',
  'reason.headToMember': 'In your team', 'reason.memberToHead': 'Your direct manager', 'reason.managers': 'Fellow manager: you coordinate across departments', 'reason.workLink': 'You work together',
  'group.HEAD': 'the direct manager', 'group.TEAM': 'a team member', 'group.PEERS': 'a colleague', 'group.ANY': 'a rater',

  // ——— fixed answers ———
  'freq.DAILY': 'Almost every day', 'freq.WEEKLY': 'About every week', 'freq.MONTHLY': 'About every month', 'freq.RARELY': 'Less than once a month',
  'ans.SET_WRITTEN': 'Yes, in writing', 'ans.SET_VERBAL': 'Yes, only verbally', 'ans.SET_NO': 'Not set yet',
  'ans.DISC_DOC': 'Yes, and there is a written trace (a message or minutes)', 'ans.DISC_VERBAL': 'Yes, verbally', 'ans.DISC_NO': 'No, not yet', 'ans.DISC_NONE': 'There are no weaknesses worth noting',
  'ans.TOLD_REG': 'Regularly', 'ans.TOLD_SOME': 'Sometimes', 'ans.TOLD_NEVER': 'Never', 'ans.TOLD_NA': 'There were no comments on my work',
  'scale.1': 'Very weak', 'scale.2': 'Weak', 'scale.3': 'Average', 'scale.4': 'Good', 'scale.5': 'Excellent',

  // ——— validation messages ———
  'err.notTeam': 'This page is for the organisation\'s team only.',
  'err.paperNoDept': 'Paper entry covers the self-evaluation and rating people only.',
  'err.rateAll': 'Please rate every item (you can choose "I don\'t know").',
  'err.badScore': 'That score is not valid.',
  'err.example': 'Write a real example ({n} characters or more) for «{item}».',
  'err.complete': 'Please complete: «{q}».',
  'err.choose': 'Please choose an answer: «{q}».',
  'err.notInList': 'This person is not on your list.',
  'err.freq': 'Choose how often you work with them.',
  'err.headDid': 'You gave a 1 or 2 — write what you did as their manager to help ({n} characters or more).',
  'err.headDisc': 'You gave a 1 or 2 — choose whether you discussed these weaknesses with them before this evaluation.',
  'err.deptNotInList': 'This department is not on your list.',
  'err.deptFreq': 'Choose how often you deal with this department.',
  'err.deptExample': 'Write a real example from your dealings with this department ({n} characters or more).',
  'err.unknownKind': 'Unknown kind of evaluation.',
  'err.adminOnly': 'Not allowed: only the evaluation admin can do this.',
  'err.notAllowed': 'Not allowed.',
  'err.pageTeamOnly': 'This page is for the team of {org} only. Open the link with your work account.',
  'err.draftTooLong': 'The draft is longer than allowed.',
  'err.noUrl': 'The personal page is not published yet. Choose «4) Publish the personal page» first.',
  'err.noPairs': 'Make the pairings first (menu 3).',

  // ——— flags (admin only) ———
  'flagName.BLAME_PATTERN': 'Manager may be blaming the team', 'flagName.STRAIGHT_LINE': 'Same score on every item', 'flagName.OUTLIER': 'Rating far from the other raters',
  'flagName.MUTUAL_HIGH': 'Possible mutual flattery', 'flagName.UNASSIGNED': 'Rating nobody asked for', 'flagName.WEAK_EVIDENCE': 'Weak example for an extreme score',
  'flagName.REL_MISMATCH': 'Relationship does not match the structure', 'flagName.BLIND_SPOT': 'Blind spot (rates self much higher)', 'flagName.LOW_COMPLETION': 'Has not finished their ratings',
  'flagName.DUPLICATE': 'Duplicate answers', 'flagName.UNKNOWN_RATER': 'Unknown rater', 'flagName.UNKNOWN_RATEE': 'Unknown person rated',
  'flagName.SELF_IN_PEER_FORM': 'Rated themselves as a colleague', 'flagName.OWN_DEPT': 'Rated their own department', 'flagName.COPIED_EVIDENCE': 'Same example copied into several items',
  'flagName.LOW_RESPONSIVENESS': 'Seen as slow to respond', 'flagName.EXCLUDED_BY_YOU': 'Excluded by you', 'flagName.NO_FOLLOW_UP': 'Criticism without follow-up by the manager',
  'flagName.NO_EXPECTATIONS': 'Expectations were never set',
  'sev.HIGH': 'High', 'sev.MED': 'Medium', 'sev.LOW': 'Low',
  'flag.DUPLICATE.detail': '{n} repeated answer(s) set aside (only the latest counts).',
  'flag.UNKNOWN_RATER.self': 'A self-evaluation from an email not in the Team tab.',
  'flag.UNKNOWN_RATER.person': 'A rater from outside the Team tab.',
  'flag.UNKNOWN_RATER.dept': 'A department rating from an email not in the Team tab.',
  'flag.UNKNOWN_RATEE.detail': 'A rating for someone not in the Team tab.',
  'flag.SELF_IN_PEER_FORM.detail': 'Rated themselves as if a colleague — excluded.',
  'flag.REL_MISMATCH.detail': 'The chosen relationship ({said}) differs from the structure ({real}) — the structure was used.',
  'flag.WEAK_EVIDENCE.detail': 'Score {v} on «{item}» with a short or unclear example.',
  'flag.COPIED_EVIDENCE.detail': 'The same example is copied into {n} items — it does not fit each item.',
  'flag.tail.excludedByYou': ' — excluded from the results by your decision.',
  'flag.tail.excludedAuto': ' — excluded automatically (write "keep" in «Review decisions» to bring it back).',
  'flag.tail.keptByYou': ' — kept in the results by your decision.',
  'flag.UNASSIGNED.detail': 'Rated someone they were not asked to rate',
  'flag.STRAIGHT_LINE.detail': 'Gave {v} on every item without distinction — possibly revenge or flattery',
  'flag.EXCLUDED_BY_YOU.detail': 'Excluded from the results by your decision.',
  'flag.LOW_RESPONSIVENESS.detail': '{n} raters see them as slow on «{item}» ({v} of 5) — read the examples in their report.',
  'flag.BLIND_SPOT.detail': 'Rates themselves ({self}) clearly higher than others do ({others}).',
  'flag.OUTLIER.lower': 'Their average ({m}) is much lower than the other raters\' ({rest}).',
  'flag.OUTLIER.higher': 'Their average ({m}) is much higher than the other raters\' ({rest}).',
  'flag.MUTUAL_HIGH.detail': 'Very high ratings exchanged between two colleagues ({a} / {b}) — read the examples.',
  'flag.NO_FOLLOW_UP.head': 'Rated {name} low on {n} item(s) ({items}) and says they did not discuss it before the evaluation — criticism without follow-up weighs on the manager more than on the member.',
  'flag.NO_FOLLOW_UP.member': 'Rated {name} low on {n} item(s) ({items}) while {name} says the manager never told them what to improve — criticism without follow-up weighs on the manager more than on the member.',
  'flag.NO_EXPECTATIONS.head': 'Expectations were not set for {name} at the start (the manager says so) — they cannot be held to "achieving what was expected" before that.',
  'flag.NO_EXPECTATIONS.member': 'Expectations were not set for {name} at the start (the member says so) — they cannot be held to "achieving what was expected" before that.',
  'flag.BLAME_PATTERN.detail': 'Rates the team ({hv}) clearly lower than others rate the same people ({ov}), while the team rates this leadership {up}',
  'flag.BLAME_PATTERN.noFollow': ', and did not follow up weaknesses with {n} team member(s)',
  'flag.BLAME_PATTERN.check': '. A signal to read the examples, not a verdict.',
  'flag.OWN_DEPT.detail': 'Rated their own department — excluded.',
  'flag.LOW_COMPLETION.detail': 'Finished {d} of {n} assigned ratings.',
  'flag.LOW_COMPLETION.noSelf': 'Finished {d} of {n} assigned ratings, and has not sent the self-evaluation.',

  // ——— results tabs ———
  'results.updated': 'Results updated. See the tabs «Progress», «Flags» and «Results by person». Nobody else can see them.',
  'results.testBanner': '⚠ Test data with made-up people — not real results',
  'results.banner': 'Private — admin only — updated {date}',
  'results.notReleasable': 'no (fewer than {n} raters)',
  'results.leadAvg': 'Leadership average', 'results.members': 'People', 'results.seenByOthers': 'How other departments see it',
  'results.membersOn': 'Its people: {item}', 'results.matrix': 'Matrix: the row rates the column',
  'results.byManager': 'manager: {a}', 'results.byThem': 'them: {a}', 'results.paper': 'paper', 'results.patternYes': '⚠ yes — read the examples',
  'col.completion.name': 'Name', 'col.completion.dept': 'Department', 'col.completion.self': 'Self-evaluation', 'col.completion.assigned': 'Assigned',
  'col.completion.done': 'Done', 'col.completion.pct': 'Progress', 'col.completion.deptForms': 'Department ratings', 'col.completion.pending': 'Still to rate',
  'col.flags.sev': 'Level', 'col.flags.type': 'Flag', 'col.flags.person': 'About', 'col.flags.rater': 'Rater', 'col.flags.detail': 'Details',
  'col.flags.raterEmail': 'Rater email (private)', 'col.flags.personEmail': 'Rated email',
  'col.people.name': 'Name', 'col.people.dept': 'Department', 'col.people.manages': 'Manages a team', 'col.people.raters': 'Raters',
  'col.people.head': 'Manager', 'col.people.team': 'Team', 'col.people.peers': 'Colleagues', 'col.people.others': 'Others\' average (core)',
  'col.people.self': 'Self', 'col.people.gap': 'Gap', 'col.people.lead': 'Team\'s view of leadership', 'col.people.strengths': 'Strengths',
  'col.people.dev': 'To develop', 'col.people.blind': 'Blind spots', 'col.people.releasable': 'Can be shared with the person', 'col.people.role': 'Role questions (others)',
  'col.summary.name': 'Name', 'col.summary.dept': 'Department', 'col.summary.title': 'Job title', 'col.summary.raters': 'Raters', 'col.summary.excluded': 'Excluded',
  'col.summary.others': 'Others\' rating', 'col.summary.self': 'Self-rating', 'col.summary.lead': 'Team\'s view of leadership', 'col.summary.recog': 'Recognition',
  'col.summary.x1': 'Achieved what was expected (manager)', 'col.summary.set': 'Were expectations set?', 'col.summary.completion': 'Finished their ratings',
  'col.summary.flags': 'Signals about them', 'col.summary.doubtful': 'Doubtful ratings they wrote', 'col.summary.band': 'First indication (not a decision)',
  'col.summary.kpi': 'Other evidence (you write)', 'col.summary.decision': 'Your decision',
  'band.notEnough': 'Not enough data', 'band.review': 'Needs a careful look', 'band.strong': 'Strong', 'band.ok': 'Fine — development plan',
  'col.stars.name': 'Name', 'col.stars.dept': 'Department', 'col.stars.recog': 'Times recognised', 'col.stars.others': 'Others\' average', 'col.stars.self': 'Self-rating',
  'col.stars.humble': 'Underrates themselves', 'col.stars.hidden': 'Quiet star', 'col.stars.why': 'What colleagues said',
  'col.blame.head': 'Manager', 'col.blame.dept': 'Department', 'col.blame.size': 'Team size', 'col.blame.headView': 'How they rate their team',
  'col.blame.othersView': 'How others rate the same team', 'col.blame.gap': 'Difference', 'col.blame.teamLead': 'Team\'s view of leadership',
  'col.blame.teamResp': 'Team\'s view of owning results', 'col.blame.peerComm': 'Colleagues\' view of communication', 'col.blame.selfLead': 'Own view of leadership',
  'col.blame.noFollow': 'Criticism without follow-up (count)', 'col.blame.noSet': 'Expectations not set (count)', 'col.blame.pattern': 'Signal: blaming the team',
  'col.account.head': 'Manager', 'col.account.member': 'Team member', 'col.account.low': 'Low items (1–2)', 'col.account.which': 'Which',
  'col.account.setHead': 'Expectations set? (manager)', 'col.account.setMember': 'Expectations set? (member)', 'col.account.disc': 'Discussed before? (manager)',
  'col.account.told': 'Was I told what to improve? (member)', 'col.account.did': 'What the manager did (their words)', 'col.account.mine': 'The manager\'s own part (their words)',
  'col.account.help': 'What the manager did in a hard moment (member\'s words)', 'col.account.noFollow': 'Criticism without follow-up',
  'dash.item': 'Item', 'dash.selfAvg': 'Self-rating (organisation average)', 'dash.othersAvg': 'Others\' rating (organisation average)',
  'dash.seenByOthers': 'As other departments see it', 'dash.peopleAvg': 'Average of its people', 'dash.completion': 'Evaluation progress %',
  'dash.chart1': 'The organisation on each item (out of 5)', 'dash.chart2': 'Departments: as others see them, and their people (out of 5)', 'dash.chart3': 'Evaluation progress by department %',

  // ——— test ———
  'test.done': 'Test run with made-up people. Results are in the tabs and reports in the folder: {folder}. When you have looked, choose «Try it: clear the test».',
  'test.confirmReal': 'Real answers already exist. The test will replace the results tabs with made-up data until you choose «Update results» again. Your answers are not touched. Continue?',
  'test.cleared': 'Test results cleared ({n} folder(s) moved to the Drive bin, recoverable for 30 days).',
  'test.example': 'Test example about «{item}»: at the monthly follow-up the report arrived two weeks late, which delayed a payment.',
  'test.start': 'Start (test)', 'test.keep': 'Keep (test)', 'test.ach': 'Test achievement', 'test.plan': 'Test plan',
  'test.deptExample': 'Test example of working between the two departments', 'test.deptSugg': 'Test suggestion',
  'test.headMine': 'Nothing — the team is the problem', 'test.teamch': 'The team does not keep deadlines',
  'test.headDid': 'Raised it in our 3 May meeting and set up a weekly follow-up table for replies', 'test.headMine2': 'I was late providing a task-tracking tool',
  'test.copied': 'Not good at this at all and never replies to us about it',

  // ——— welcome text: what, why, values, how (page, email, paper) ———
  'intro.title': 'Before we start',
  'intro.openingEmail': 'This is your personal invitation to the 360-degree performance evaluation {cycle}, which we start today for the whole team of {org}.',
  'intro.openingPage': 'This is your personal page for the 360-degree performance evaluation {cycle}.',
  'intro.what360': 'A 360-degree evaluation means each of us rates ourselves, and is rated by our manager and the colleagues we work with, so the picture is complete from every side, not from one.',
  'intro.whyTitle': 'Why are we doing this evaluation?',
  'intro.why1': 'Together we review how we have worked {period}: where we did well, where we need to grow, and the good efforts not everyone sees — so each of us gets a clear plan for development and support, for the good of our organisation and our culture.',
  'intro.why2': 'What you write honestly helps a colleague grow, and helps us see where we need support and improvement.',
  'intro.valuesTitle': 'Our values in this evaluation',
  'intro.stepsTitle': 'How do I fill it in?',
  'intro.step1': 'Three parts: rate yourself, then colleagues shown to you because you work with them, then departments you deal with.',
  'intro.step2': 'Tap a number from 1 to 5; the lines under each item explain what it means. If you have not seen it yourself, choose "I don\'t know" — it counts against nobody.',
  'intro.step3': 'Rate the whole period, not one moment.',
  'intro.step4': 'It takes about 10 minutes for yourself and 3 minutes per person.',
  'intro.autosave': 'Your answers save automatically, so you can stop and come back, and edit after sending until the deadline.',
  'intro.closing': 'Thank you for your honesty and your time.',

  // ——— email ———
  'email.hello': 'Hello {name},',
  'email.tasks': 'What is asked of you:', 'email.tasksBy': 'What is asked of you, before {date}:',
  'email.taskSelf': 'Your self-evaluation (about 10 minutes)',
  'email.taskPersons': 'Rating {n} colleague(s) shown to you because you work with them (about 3 minutes each): {names}',
  'email.taskDepts': 'Rating {n} department(s) you deal with (2 minutes each)',
  'email.openPage': 'Open your personal page (with your work account):',
  'email.button': 'Open my evaluation page', 'email.openWith': 'Open it with your work account',
  'email.confidential': 'Your evaluation is confidential.',
  'email.inviteSubject': 'Invitation: confidential 360 evaluation – {org}',
  'email.previewSubject': '[Preview] Invitation: confidential 360 evaluation – {org}',
  'email.previewName': 'Admin',
  'email.previewSent': 'A preview of the invitation was sent to you only. Nothing was sent to anyone else.',
  'email.confirmInvite': 'A personal invitation with one button will be emailed to {n} people. Send now?',
  'email.invitesSent': '{n} invitation(s) sent.',
  'email.invitesPartial': '{n} invitation(s) sent; {left} not yet (Google limits how many emails can be sent per day and per run). Choose the same menu item again later: nobody receives it twice.',
  'email.allInvited': 'Everyone has already received the invitation. To nudge people, use «Send reminders».',
  'remind.none': 'Everyone has finished. No reminder needed.',
  'remind.confirm': 'A friendly reminder will be emailed to {n} people who have not finished, with what is left and the button to their page. Send now?',
  'remind.body': 'A friendly reminder to finish the confidential 360 evaluation. You have {n} rating(s) left; your page shows exactly which.',
  'remind.bodySelf': 'A friendly reminder to finish the confidential 360 evaluation. You have {n} rating(s) left, including your self-evaluation; your page shows exactly which.',
  'remind.subject': 'Reminder: 360 evaluation – {org}', 'remind.button': 'Finish my ratings', 'remind.sent': '{n} reminder(s) sent.', 'remind.partial': '{n} reminder(s) sent; {left} not sent because the daily email limit of Google was reached. Try again tomorrow.',

  // ——— reports ———
  'reports.done': 'Reports made in the folder: {folder}. The folder is yours alone; nobody sees a report until you decide.',
  'reports.partial': 'Reports made for {d} of {n} people so far (Google limits how long one run can take). Choose the same menu item again to continue in the same folder: {folder}.',
  'reports.folder': 'Reports – private –', 'reports.testFolder': 'TEST – reports –',
  'reports.adminFolder': 'Individual reports – admin copy', 'reports.staffFolder': 'Individual reports – employee copy (share only when you decide)',
  'report.item': 'Item', 'report.chartSelf': 'How you see yourself and how others see you (out of 5)', 'report.yourSelf': 'Your self-rating', 'report.others': 'Others\' rating',
  'report.testPrefix': 'TEST – ', 'report.testNote': 'Test data with made-up people.',
  'report.staffTitle': '360 report – {name} – employee copy', 'report.adminTitle': '360 report – {name} – private',
  'report.title': '360-degree evaluation report – {cycle}',
  'report.staffIntro': 'This report reviews your work since the start of the period, as you see it and as the people who work with you see it — for the good of our organisation and our culture, and so we can agree together on a clear plan for development and support. Ratings are grouped; no rater\'s name appears.',
  'report.staffTooFew': 'Not enough people rated you to show results while keeping raters anonymous. We will review your work in a conversation with your manager.',
  'report.overview': 'The overall picture', 'report.of5': 'out of 5', 'report.othersAvg': 'Average rating from people who work with you', 'report.selfAvg': 'Your average self-rating', 'report.nRaters': 'Number of people who rated you',
  'report.itemTooFew': '—: fewer than {n} people answered this item, so its score is not shown, to keep raters anonymous.',
  'report.scale': 'Scale: 1 very weak · 2 weak · 3 average · 4 good · 5 excellent.',
  'report.byItem': 'Rating by item', 'report.strengthsDev': 'Strengths and areas to develop',
  'report.strengthsYou': 'Your main strengths, as the people who work with you see them:', 'report.devYou': 'What you can develop most:',
  'report.reflect': 'Worth reflecting on (a gap between how you see yourself and how others see you):',
  'report.overYou': '{item}: you see it in yourself more than others do ({self} vs {others}) — a chance to ask for examples and grow.',
  'report.underYou': '{item}: others see it in you more than you do ({others} vs {self}) — trust this strength.',
  'report.leadYou': 'Your leadership of your team', 'report.leadItem': 'Leadership item', 'report.teamAndManager': 'Your team and manager',
  'report.leadTooFew': 'Fewer than {n} people rated your leadership, so the scores are not shown to protect them; they will be discussed in your conversation.',
  'report.saidYou': 'What the people who work with you said (no names)',
  'report.keep': 'Keep doing:', 'report.start': 'Start doing:', 'report.stop': 'Stop doing:', 'report.easierYou': 'What would make working with you easier:', 'report.easier': 'What would make working with them easier:',
  'report.examples': 'Examples colleagues gave:',
  'report.recogYou': 'Recognition from colleagues', 'report.recogYouText': '{n} colleague(s) named you as someone whose effort helped them or deserves recognition. Thank you.',
  'report.expectedYou': 'What was achieved against what was expected (in your words)', 'report.expectYou': 'What was expected of you, as you understood it:', 'report.achYou': 'Your achievements:', 'report.contribYou': 'Your share of the team\'s numbers:',
  'report.plan': 'Agreed development plan', 'report.planYou': 'Your plan, as you proposed it:',
  'report.agreed': 'What we agreed in our conversation:', 'report.reply': 'Your response or comments on this report:',
  'report.signatures': 'Employee: ____________    Direct manager: ____________    Admin: ____________    Date: ________',
  'report.adminOnly': 'Private — for the admin\'s review only — not yet shown to the employee.',
  'report.releasable': 'Can be shared with the employee after your review: yes ({n} raters).',
  'report.notReleasable': 'Cannot be shared with the employee: {n} raters is fewer than {min}, and showing it could reveal who the raters are.',
  'report.excluded': '{n} rating(s) excluded (not assigned, the same score everywhere, or your decision) — details in the Flags tab.',
  'report.summary': 'Summary', 'report.measure': 'Measure', 'report.value': 'Value', 'report.count': 'Count',
  'report.othersCore': 'Others\' average (core items)', 'report.selfCore': 'Self-rating (core items)', 'report.byGroup': 'Raters: manager / team / colleagues', 'report.recogCount': 'Times recognised by colleagues',
  'report.scaleWeighted': 'Scale: 1 very weak · 2 weak · 3 average · 4 good · 5 excellent. Averages are weighted by how often the rater works with the person.',
  'report.byItemWho': 'Rating by item and by who rated', 'report.merged': 'merged',
  'report.self': 'Self', 'report.manager': 'Manager', 'report.team': 'Team', 'report.peers': 'Colleagues', 'report.gap': 'Gap',
  'report.mergedNote': '"merged": fewer than {n} raters in this group, so their scores are included only in "Others" to protect them.',
  'report.strengths': 'Main strengths (as others see them):', 'report.dev': 'Main areas to develop:',
  'report.blind': 'Blind spots (a clear gap between self-view and others\' view):',
  'report.over': '{item}: sees themselves better than others do ({self} vs {others})', 'report.under': '{item}: underrates themselves — others see them better ({others} vs {self})',
  'report.lead': 'Leadership', 'report.compare': 'Comparison: how they see their team, and how their team sees them',
  'report.headView': 'Their rating of their team members', 'report.othersView': 'Others\' rating of the same team members', 'report.teamLead': 'Team\'s view of their leadership',
  'report.teamResp': 'Team\'s view of owning the team\'s results', 'report.peerComm': 'Colleagues\' view of their communication',
  'report.patternNote': '⚠ Signal: rates the team clearly lower than other raters do, while the team rates this leadership and ownership low. Read the examples below before drawing any conclusion; this is not a verdict.',
  'report.handling': 'How they dealt with weaknesses in their team',
  'report.weakMembers': 'Members rated low (1 or 2) on at least one item', 'report.discussed': 'Of those: says they discussed it before', 'report.noFollow': 'Of those: criticism without follow-up',
  'report.notWritten': 'Members whose expectations were not set in writing (by either side)',
  'report.didSaid': 'What they say they did as a manager:', 'report.mineSaid': 'What they say was their own part:',
  'report.expected': 'What was achieved against what was expected', 'report.expect': 'What was expected, as they understood it:', 'report.ach': 'Their achievements:', 'report.contrib': 'Their share of the team\'s numbers:',
  'report.x1Head': 'Achieved what was expected — manager\'s view (of 5)', 'report.setHead': 'Were expectations set? — manager', 'report.setThem': 'Were expectations set? — them',
  'report.headExample': 'Manager\'s example: «{t}»',
  'report.evidence': 'Examples and evidence (no names)', 'report.scoreBy': 'Score {v} ({who})', 'report.noExamples': 'No examples recorded.',
  'report.notes': 'Raters\' notes: start / stop / keep', 'report.recog': 'Recognition from colleagues', 'report.recogText': '{n} colleague(s) named them as someone whose effort helped them or deserves recognition.',
  'report.selfWords': 'The self-evaluation in their own words', 'report.noSelf': 'Did not send a self-evaluation.',
  'report.next': 'Next steps (after the conversation)', 'report.nextSession': 'Notes from the one-to-one conversation:', 'report.nextReply': 'The employee\'s written response:',
  'report.nextPlan': 'Agreed actions (also write them in the «Agreed actions» tab):',
  'report.readWith': 'This evaluation covers the period since the start and is read together with other evidence of the work.',
  'report.signaturesAdmin': 'Employee: ____________    Direct manager: ____________    Admin approval: ____________    Date: ________',
  'report.orgTitleDoc': '360 report – organisation and departments – private', 'report.orgTitle': '360-degree evaluation – organisation report – {cycle}',
  'report.participation': 'Participation', 'report.included': 'People included', 'report.withRatings': 'People rated by others', 'report.withSelf': 'Sent a self-evaluation', 'report.flagCount': 'Flags to review',
  'report.orgWeak': 'The main weaknesses across the organisation', 'report.orgAvg': 'Organisation average', 'report.below3': 'Share rated below 3',
  'report.depts': 'Departments: as other departments see them', 'report.total': 'Overall', 'report.deptExamples': '{dept} – examples from other departments',
  'report.from': 'From {d}', 'report.sugg': 'suggestion', 'report.matrixCorner': 'Rates ↓ / Rated →',
  'report.managers': 'Managers: leadership and the blame signal', 'report.stars': 'Quiet stars and recognition', 'report.none': 'None.',
  'report.starLine': '{name} ({dept}) – recognised {n} time(s), others\' average {v}',
  'report.heat': 'Performance map by person', 'report.codes': 'Codes:',
  'report.slow': 'Responsiveness: seen as slow by colleagues, or not finishing their ratings', 'report.highFlags': 'High-level flags',
  'report.flagsTab': 'All flags and rater names are in the Flags tab of the evaluation sheet.',

  // ——— paper forms ———
  'paper.none': 'Everyone in the Team tab has a work email, so no paper forms are needed.',
  'paper.folder': 'Paper forms –',
  'paper.done': '{n} paper form(s) made in the folder: {folder}. Print them. When they come back, choose «Enter answers from paper forms» in the menu and type the answers exactly as written.',
  'paper.entryIntro': 'Click a name to open their page, then type the answers from their paper form exactly as written. Only you can open these links.',
  'paper.noPage': 'Publish the personal page first: menu «4) Publish the personal page».',
  'paper.title': '360 paper form – {name}', 'paper.heading': 'Confidential 360 evaluation – {cycle}',
  'paper.opening': 'This is your paper form for the 360-degree performance evaluation.',
  'paper.howTitle': 'How do I fill in the paper form?',
  'paper.how1': 'Two parts: rate yourself, then colleagues shown to you because you work with them.',
  'paper.how2': 'Write clearly. Circle one score per item. The line under each item explains what it means.',
  'paper.how3': 'After a 1, 2 or 5, write an example: what happened, roughly when, and the result ({n} characters or more).',
  'paper.how4': 'If you did not see it yourself, circle "I don\'t know" — it counts against nobody.',
  'paper.how5': 'Rate the whole period, not one moment. If there is a personal disagreement between you, rate the work only.',
  'paper.how6': 'Hand it in, in a sealed envelope, to the evaluation admin only. Deadline: {date}.',
  'paper.circle': 'Circle one score', 'paper.example': 'Real example (required after 1, 2 or 5)', 'paper.circleOne': 'Circle one:',
  'paper.part1': 'Part 1: your self-evaluation', 'paper.partN': 'Part {n}: rating {name}',
  'paper.recog': 'Recognition (optional): whose effort helped you, or deserves credit not everyone sees? (up to 3 names)',
  'paper.sign': 'Date: ____________      Signature (optional): ____________',
  'paper.office': 'For the office: entered into the system on ________ by ________',

  // ——— the personal page ———
  'ui.pageTitle': '360 evaluation – {org}',
  'ui.hello': 'Hello {name}', 'ui.introTitle': 'Before we start', 'ui.whyTitle': 'Why are we doing this evaluation?', 'ui.valuesTitle': 'Our values in this evaluation',
  'ui.stepsTitle': 'How do I fill it in?', 'ui.closing': 'Thank you for your honesty and your time.',
  'ui.start': 'Got it — let\'s start', 'ui.continue': 'Continue the evaluation ({d} of {n} done)',
  'ui.paperEntry': '📝 Entering a paper form on behalf of: {name} — copy the answers exactly as written.',
  'ui.homeSub': 'Confidential 360 evaluation', 'ui.deadline': 'deadline:',
  'ui.allDone': 'You have finished every rating asked of you — thank you 🌿', 'ui.progress': '{d} of {n} done',
  'ui.selfTitle': '1) Your self-evaluation', 'ui.selfRow': 'Your self-evaluation', 'ui.selfTime': 'Once · about 10 minutes',
  'ui.personsTitle': '2) People to rate', 'ui.personsSub': 'They appear because you work with them · about 3 minutes each',
  'ui.deptsTitle': '3) Departments you deal with', 'ui.deptsSub': 'Departments your team works with · 2 minutes each. If you do not deal with one, open it and press «{skip}».',
  'ui.homeNote': '🔒 Your evaluation is confidential · 💾 answers save automatically and you can edit until the deadline.',
  'ui.backToIntro': 'Before we start: why we do this evaluation and how to fill it in',
  'ui.draftEdit': '✎ You have a change not sent yet — press «Continue», then «Send»', 'ui.draftStarted': '✎ Started — your answers are saved',
  'ui.done': '✓ Done', 'ui.resume': 'Continue', 'ui.edit': 'Edit', 'ui.begin': 'Start', 'ui.back': '← Back (what you wrote is saved)',
  'ui.scaleMeaning': '5 = always, a model for others · 4 = in most situations · 3 = sometimes · 2 = rarely, needs clear improvement · 1 = almost never, and it hurts the work',
  'ui.extremeNote': 'After a 1, 2 or 5, write an example you saw yourself: a higher or lower score needs something to support it.',
  'ui.naNote': '"I don\'t know": I have not seen this myself. It counts against nobody.',
  'ui.na': 'I don\'t know', 'ui.naPicked': 'I don\'t know — I have not seen this myself, and it does not count against them',
  'ui.saving': 'Saving your draft…', 'ui.saved': '✓ Your answers saved automatically', 'ui.savedLocal': '✓ Saved on this device', 'ui.savedLocalRetry': '✓ Saved on this device — we will try again',
  'ui.restored': '↺ We picked up where you stopped — your unsent answers are saved as they were.', 'ui.restoredShort': '↺ Your draft was restored', 'ui.autosaveHint': 'Your answers save automatically as you write',
  'ui.more': 'More…', 'ui.evidenceExample': 'Example: in August the monthly report arrived a week late with no warning, so the donor update was delayed.',
  'ui.chars': '{n} characters ({min} or more needed)', 'ui.evidenceLabel': 'You chose {v} — give an example you saw yourself: what happened? roughly when? what was the result?',
  'ui.needDid': 'You chose 1 or 2, so please write the support you gave to help improve it ({n} characters or more)',
  'ui.needAnswer': 'Choose an answer or complete the question outlined in red', 'ui.missing': 'Some items have no score or no example — see what is outlined in red',
  'ui.send': 'Send the evaluation', 'ui.sending': 'Sending…', 'ui.sent': 'Your evaluation was sent ✓', 'ui.error': 'Something went wrong, please try again',
  'ui.offline': 'Your evaluation has not arrived yet. Check the internet and try again — what you wrote is saved',
  'ui.rating': 'Rating: {name}', 'ui.whyShown': 'Why you see this person:', 'ui.whyShownHelp': 'They appear because you work together.',
  'ui.describesOther': 'The lines under each item describe the person you are rating.', 'ui.conflict': 'If there is a personal disagreement between you, rate the work only.',
  'ui.freqQ': 'How often do you work with them?', 'ui.freqHelp': 'This helps us understand how well you know their work.',
  'ui.roleTitle': 'About this kind of work', 'ui.roleSub': 'Questions about this kind of work. If you have not seen it, choose «{na}».',
  'ui.leadTitle': 'Leadership', 'ui.leadSub': 'How they lead their team, as you see it.', 'ui.leadNa': 'If you have not seen how they lead their team, choose "I don\'t know".',
  'ui.headTitle': 'Achieving what was expected, and your part as their manager',
  'ui.headIntro': 'An evaluation is shared between a manager and the team. These questions help us see the whole picture, and we may compare them with the team\'s answers. Answer honestly: the goal is to support improvement, not to blame.',
  'ui.memberTitle': 'You and your manager', 'ui.memberIntro': 'Rating your manager helps them support you better. Write respectfully and with an example.',
  'ui.notesTitle': 'Short notes', 'ui.needFreq': 'Choose how often you work with them',
  'ui.describesSelf': 'The lines under each item describe you. Choose the score that honestly fits you — the goal is to see together where you shine and where we can help you grow.',
  'ui.selfLead': 'Your leadership of your team', 'ui.selfReview': 'Looking back at your work', 'ui.selfReviewSub': 'Honesty here counts for you, not against you',
  'ui.recogTitle': 'Recognising colleagues (optional)', 'ui.recogSub': 'Whose effort helped you, or deserves credit not everyone sees? Up to 3 people',
  'ui.pickColleague': '— choose a colleague —', 'ui.recogWhy': 'What did each of them do, exactly?', 'ui.recogWhyHelp': 'For each colleague, what they did, starting with their name.',
  'ui.deptRating': 'Rating a department: {name}', 'ui.deptHint': 'Rate the department as a whole, not one person: how does it work with you and your team? ("we" means you and your team.)',
  'ui.deptFreqQ': 'How often do you deal with this department?',
  'ui.deptSkip': 'I have not dealt with this department', 'ui.deptSkipQ': 'You do not deal with this department?',
  'ui.deptSkipConfirm': 'You have not dealt with {name}? That will be recorded instead of a rating.',
  'ui.deptExample': 'A real example from your dealings with this department', 'ui.deptExampleHelp': 'What happened? When? What was the result?',
  'ui.deptSugg': 'What one change by this department would improve the work between you?',
  'ui.needDeptFreq': 'Choose how often you deal with this department', 'ui.needDeptExample': 'Write a real example ({n} characters or more)',
  // after the results: the conversation, agreed actions and the follow-up
  'tab.ACTIONS': 'Agreed actions',
  'col.actions.name': 'Name', 'col.actions.email': 'Email', 'col.actions.manager': 'Manager (email)', 'col.actions.action': 'Agreed action',
  'col.actions.support': 'Support needed', 'col.actions.due': 'By when', 'col.actions.done': 'Done (yes/no)', 'col.actions.checked': 'Last follow-up',
  'note.actions': 'After each conversation, write what you agreed: one row per action (add rows as needed). About 3 months later, «Follow up agreed actions» emails each manager the actions that are not done yet.',
  'menu.followUp': 'Follow up agreed actions (emails managers)',
  'followUp.none': 'There are no open actions in the «Agreed actions» tab. Write the agreed actions there first.',
  'followUp.confirm': 'Email {n} manager(s) the agreed actions of their team that are not done yet?',
  'followUp.subject': '{org}: agreed actions to follow up',
  'followUp.intro': 'After the 360 evaluation we agreed these actions with your team. Please check in with each person: what is done, what is stuck, and what support they need from you.',
  'followUp.by': 'by {date}',
  'followUp.ask': 'Reply to this email with a one-line update for each, so they can be marked done.',
  'followUp.sent': 'Follow-up sent to {n} manager(s).',
  'reports.doneNext': 'Next: hold one conversation with each person, and write what you agree in the «Agreed actions» tab.',
  'reports.calendar': 'Add a reminder to my Google Calendar for {date}: follow up the agreed actions',
  'reports.calendarTitle': '{org}: follow up the agreed actions from the 360 evaluation',
  'reports.calendarDetails': 'In the evaluation sheet: menu «360 evaluation» → «Follow up agreed actions».',
  'report.convTitle': 'Preparing the conversation',
  'report.conv1': 'Meet in private, with enough time (about 45 minutes). Start with the purpose: to help them grow, not to judge.',
  'report.conv2': 'Ask first how they see their own year, and listen before you share the results.',
  'report.conv3': 'Go through the employee copy together: strengths first, then one or two areas to develop, with the examples.',
  'report.conv4': 'Never guess or reveal who wrote what, even if they ask.',
  'report.conv5': 'Agree two or three concrete actions: what, the support they need, and by when. Write them in the «Agreed actions» tab.',
  'report.actAction': 'Action', 'report.actSupport': 'Support needed', 'report.actWhen': 'By when',
  'guide.step13': '13) After the conversations: write what you agreed in the «Agreed actions» tab. About 3 months later, «Follow up agreed actions» reminds each manager.',
  // asking managers who works with whom
  'menu.askManagers': 'Ask managers who works with whom (optional)',
  'ask.noPage': 'Publish the personal page first: menu «4) Publish the personal page». It sends nothing to anyone, and managers use the same page.',
  'ask.noManagers': 'Nobody in the Team tab manages anyone yet. Fill in the Manager column first.',
  'ask.confirm': 'Email {n} manager(s) a short page where they list who each member of their team works with outside the team?',
  'ask.subject': '{org}: who does your team work with?',
  'ask.intro': 'We are preparing our 360 evaluation. Each person will be rated by the colleagues they really work with, so we need your help: for each person in your team, who outside the team do they work with closely, and on what?',
  'ask.how': 'It takes about 5 minutes. Your team:',
  'ask.button': 'Open the short page',
  'ask.sent': 'Sent to {n} manager(s). Their answers appear in the «Work links» tab, marked with their name. When they have answered: «2) Check my team and links», then «3) Make the pairings».',
  'links.title': 'Who does your team work with?',
  'links.intro': 'For each person, add the colleagues outside your team they work with closely, and what they work on together. This decides who rates whom, so add only real, regular work. You and their teammates are included automatically.',
  'links.already': 'Already listed:',
  'links.pick': 'Choose a colleague',
  'links.reason': 'What they work on together (the colleague will see this)',
  'links.add': 'Add another colleague',
  'links.send': 'Send',
  'links.sending': 'Sending…',
  'links.sent': 'Thank you. {n} new work link(s) added. You can open this page again later to add more.',
  'links.none': 'Nothing to send yet: choose a colleague and write what they work on together.',
  'links.needReason': 'Write what they work on together for every colleague you chose.',
  'links.error': 'Something went wrong. Please reload the page and try again.',
  'links.notManager': 'This page is for people who manage a team. If you think this is wrong, contact the evaluation admin.',
  'links.fromManager': 'Suggested by {name}'
};
